#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
filter=""
dry="0"

while [[ $# -gt 0 ]]; do
  echo "ARG: \"$1\""
  if [[ "$1" == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

execute() {
  log "execute: $*"
  if [[ "$dry" == "1" ]]; then
    return
  fi
  "$@"
}

log() {
  if [[ "$dry" == "1" ]]; then
    echo "DRY RUN: $*"
  else
    echo "$*"
  fi
}

log "$script_dir -- $filter"

cd "$script_dir" || exit 1

scripts=$(find runs -maxdepth 1 -mindepth 1 -type f)

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $script"
    continue
  fi

  execute "./$script"
done
