color0       #4B4A4C
color8       #A19F9C
color1       #878A6B
color9       #878A6B
color2       #C87D76
color10      #C87D76
color3       #94AE4E
color11      #94AE4E
color4       #7EB4B2
color12      #7EB4B2
color5       #C4A886
color13      #C4A886
color6       #DED9D1
color14      #DED9D1
color7       #E6E4E0
color15      #E6E4E0