#!/usr/bin/env bash
set -euo pipefail

sudo apt -y install curl git tar unzip kitty \
  rofi wget gh tmux jq cmake gettext lua5.1 liblua5.1-0-dev \
  ripgrep fzf gcc xclip luajit stow zoxide

sh -c "$(git config --global alias.co checkout)"
sh -c "$(git config --global alias.ci commit)"
sh -c "$(git config --global alias.st status)"
sh -c "$(git config --global alias.br branch)"
sh -c "$(git config --global alias.hi 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short')"
sh -c "$(git config --global alias.p pull)"
sh -c "$(git config --global alias.ps push)"

# Install neofetch from source
if [ ! -d "$HOME/neofetch" ]; then
  git clone https://github.com/dylanaraps/neofetch.git "$HOME/neofetch"
fi
cd "$HOME/neofetch" || exit
sudo make install
