#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  brew install curl git tar unzip neofetch kitty wget gh tmux jq cmake

else
  echo "Linux detected"
  sudo apt -y install curl git tar unzip neofetch kitty rofi wget gh tmux jq cmake
fi

sh -c "$(git config --global alias.co checkout)"
sh -c "$(git config --global alias.ci commit)"
sh -c "$(git config --global alias.st status)"
sh -c "$(git config --global alias.br branch)"
sh -c "$(git config --global alias.hi 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short')"
sh -c "$(git config --global alias.p pull)"
sh -c "$(git config --global alias.ps push)"

