#!/usr/bin/env bash

dist=$(grep DISTRIB_ID /etc/*-release | awk -F '=' '{print $2}')

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  sudo brew install curl git tar unzip neofetch kitty rofi wget gh tmux jq cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit

else
  echo "Linux detected"
  if [[ "$dist" == "Ubuntu" ]]; then
    echo "Ubuntu"
    sudo apt -y install curl git tar unzip neofetch kitty rofi wget gh tmux jq cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit
  else
    echo "Arch BTW"
    sudo pacman -S --noconfirm curl git tar unzip neofetch kitty rofi wget gh tmux jq cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit
  fi
fi

sh -c "$(git config --global alias.co checkout)"
sh -c "$(git config --global alias.ci commit)"
sh -c "$(git config --global alias.st status)"
sh -c "$(git config --global alias.br branch)"
sh -c "$(git config --global alias.hi 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short')"
sh -c "$(git config --global alias.p pull)"
sh -c "$(git config --global alias.ps push)"
