#!/usr/bin/env bash

version="v0.11.0"
if [ -n "$NVIM_VERSION" ]; then
  version="$NVIM_VERSION"
fi

echo "version: \"$version\""

rm /usr/local/bin/nvim
rm -r /usr/local/share/nvim/
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

# neovim btw
if [ ! -d "$HOME"/neovim ]; then
  rm -rf "$HOME"/neovim
  git clone https://github.com/neovim/neovim.git "$HOME"/neovim
fi

cd "$HOME"/neovim || exit 1

git -C ~/neovim fetch --all

git -C ~/neovim checkout "$version"

make -C ~/neovim clean
make -C ~/neovim CMAKE_BUILD_TYPE=Release
make -C ~/neovim CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim"
sudo make -C ~/neovim install

wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
tar zxpf luarocks-3.11.1.tar.gz
cd luarocks-3.11.1 || exit
./configure && make && sudo make install
sudo luarocks install luacheck --force

rm -r ~/neovim/build/

echo "Neovim installed, if this script is launched single, add export PATH="$HOME/neovim/bin:$PATH" and please reload .zshrc"
