#!/usr/bin/env bash

version="v0.11.0"
if [ -n "$NVIM_VERSION" ]; then
  version="$NVIM_VERSION"
fi

echo "version: \"$version\""

rm /usr/local/bin/nvim
rm -r /usr/local/share/nvim/
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}

# neovim btw
if [ ! -d "$HOME"/personal/neovim ]; then
  rm -rf "$HOME"/personal/neovim
  git clone https://github.com/neovim/neovim.git "$HOME"/personal/neovim

fi

dist=$(grep DISTRIB_ID /etc/*-release | awk -F '=' '{print $2}')

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  sudo brew install cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit

else
  echo "Linux detected"
  if [[ "$dist" == "Ubuntu" ]]; then
    echo "Ubuntu"
    sudo apt -y install cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit
  else
    echo "Arch BTW"
    sudo pacman -S --noconfirm cmake gettext lua5.1 liblua5.1-0-dev ripgrep fzf gcc xclip luajit
  fi
fi

cd "$HOME"/personal/neovim || exit 1

git -C ~/personal/neovim fetch --all

git -C ~/personal/neovim checkout "$version"

make -C ~/personal/neovim clean
make -C ~/personalneovim CMAKE_BUILD_TYPE=RelWithDebInfo
make -C ~/personal/neovim install

wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
tar zxpf luarocks-3.11.1.tar.gz
cd luarocks-3.11.1 || exit
./configure && make && sudo make install
sudo luarocks install luacheck

source ~/.zshrc

