#!/usr/bin/env bash

echo "Arch BTW"
sudo pacman -Sy bat btop tldr rust

# install atuin, lsd and dust
cargo install atuin
cargo install lsd
cargo install du-dust

# Install font

TEMP_DIR=$(mktemp -d)

wget -O "$TEMP_DIR/font.zip" "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.0/CascadiaCode.zip"

unzip "$TEMP_DIR/font.zip" -d "$TEMP_DIR"

sudo mv "$TEMP_DIR"/*.{ttf,otf} /usr/local/share/fonts/

# Update the font cache
fc-cache -f -v

rm -rf "$TEMP_DIR"
