#!/usr/bin/env bash

dist=$(grep DISTRIB_ID /etc/*-release | awk -F '=' '{print $2}')

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  brew install zsh
else
  echo "Linux detected"
  if [[ "$dist" == "Ubuntu" ]]; then
    echo "Ubuntu"
    sudo apt -y install zsh fonts-powerline
  else
    echo "Arch BTW"
    sudo pacman -S --noconfirm zsh
  fi
fi

hash -r
sudo chsh -s "$(which zsh)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

cp -r env/.oh-my-zsh ~/
cp env/.zshrc ~/.zshrc
cp env/.p10k.zsh ~/.p10k.zsh

git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

source ~/.zshrc
echo "source ~/.zshrc"
