#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  brew y install zsh
else
  echo "Linux detected"
  sudo apt -y install zsh
fi

hash -r
sudo chsh -s "$(which zsh)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

cp -r env/.oh-my-zsh ~/
cp env/.zshrc ~/.zshrc ~/
cp env/.p10k.zsh ~/.p10k.zsh ~/

git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ~/fast-syntax-highlighting

source ~/.zshrc
echo "source ~/.zshrc"
