#!/usr/bin/env bash

echo "Copying dotfiles"
pwd

cp -r env/.config ~/

if [ ! -d "$HOME"/personal/nvim ]; then
  rm -rf "$HOME"/personal/nvim
  git clone https://github.com/javiersanzgarcia/LazyVim.git "$HOME"/personal/nvim
fi

rm -rf "$HOME"/.config/nvim
cp -r "$HOME"/personal/nvim "$HOME"/.config
chmod -R 777 "$HOME"/.config/nvim
rm -rf "$HOME"/personal

git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
tmux source "$HOME"/.config/tmux/tmux.conf

source ~/.zshrc
