#!/usr/bin/env bash

echo "Installing LazyVim"

if [ ! -d "$HOME"/personal ]; then
  mkdir "$HOME"/personal
fi

if [ ! -d "$HOME"/personal/nvim ]; then
  rm -rf "$HOME"/personal/nvim
  git clone https://github.com/javiersanzgarcia/LazyVim.git "$HOME"/personal/nvim
fi

rm -rf "$HOME"/.config/nvim
cp -r "$HOME"/personal/nvim "$HOME"/.config
chmod -R 777 "$HOME"/.config/nvim
rm -rf "$HOME"/personal
