#!/usr/bin/env bash

# Install windsurf

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Mac detected"
  brew install windsurf
else
  echo "Linux detected"
  echo "Ubuntu"
  curl -fsSL "https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/windsurf.gpg" | sudo gpg --dearmor -o /usr/share/keyrings/windsurf-stable-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/windsurf-stable-archive-keyring.gpg arch=amd64] https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt stable main" | sudo tee /etc/apt/sources.list.d/windsurf.list >/dev/null
  sudo apt-get update
  sudo apt-get upgrade windsurf

fi

windsurf --install-extension 1tontech.angular-material
windsurf --install-extension aaron-bond.better-comments
windsurf --install-extension alexiv.vscode-angular2-files
windsurf --install-extension angular.ng-template
windsurf --install-extension anseki.vscode-color
windsurf --install-extension aykutsarac.jsoncrack-vscode
windsurf --install-extension bierner.emojisense
windsurf --install-extension bradlc.vscode-tailwindcss
windsurf --install-extension chakrounanas.turbo-console-log
windsurf --install-extension christian-kohler.npm-intellisense
windsurf --install-extension codeium.windsurfpyright
windsurf --install-extension cyrilletuzi.angular-schematics
windsurf --install-extension davidanson.vscode-markdownlint
windsurf --install-extension dbaeumer.vscode-eslint
windsurf --install-extension deerawan.vscode-faker
windsurf --install-extension docsmsft.docs-preview
windsurf --install-extension donjayamanne.githistory
windsurf --install-extension dracula-theme.theme-dracula
windsurf --install-extension dsznajder.es7-react-js-snippets
windsurf --install-extension eamodio.gitlens
windsurf --install-extension ecmel.vscode-html-css
windsurf --install-extension editorconfig.editorconfig
windsurf --install-extension eliverlara.andromeda
windsurf --install-extension equimper.react-native-react-redux
windsurf --install-extension equinusocio.vsc-material-theme
windsurf --install-extension equinusocio.vsc-material-theme-icons
windsurf --install-extension esbenp.prettier-vscode
windsurf --install-extension formulahendry.terminal
windsurf --install-extension gerane.theme-monokai
windsurf --install-extension glenn2223.live-sass
windsurf --install-extension gruntfuggly.todo-tree
windsurf --install-extension hbenl.vscode-test-explorer
windsurf --install-extension humao.rest-client
windsurf --install-extension ibm.output-colorizer
windsurf --install-extension infinity1207.angular2-switcher
windsurf --install-extension john-crowson.angular-file-changer
windsurf --install-extension johnpapa.angular-essentials
windsurf --install-extension johnpapa.angular2
windsurf --install-extension johnpapa.vscode-peacock
windsurf --install-extension johnpapa.winteriscoming
windsurf --install-extension kisstkondoros.vscode-gutter-preview
windsurf --install-extension loiane.angular-extension-pack
windsurf --install-extension lucono.karma-test-explorer
windsurf --install-extension mariusalchimavicius.json-to-ts
windsurf --install-extension mechatroner.rainbow-csv
windsurf --install-extension mhutchie.git-graph
windsurf --install-extension michaelzhou.fleet-theme
windsurf --install-extension mikael.angular-beastcode
windsurf --install-extension mikestead.dotenv
windsurf --install-extension ms-ceintl.vscode-language-pack-es
windsurf --install-extension ms-python.debugpy
windsurf --install-extension ms-python.python
windsurf --install-extension ms-vscode.test-adapter-converter
windsurf --install-extension ms-vscode.vscode-typescript-next
windsurf --install-extension msjsdiag.vscode-react-native
windsurf --install-extension natewallace.angular2-inline
windsurf --install-extension natqe.reload
windsurf --install-extension obenjiro.arrr
windsurf --install-extension pflannery.vscode-versionlens
windsurf --install-extension pkief.material-icon-theme
windsurf --install-extension quicktype.quicktype
windsurf --install-extension rctay.karma-problem-matcher
windsurf --install-extension richie5um2.vscode-sort-json
windsurf --install-extension rust-lang.rust-analyzer
windsurf --install-extension rvest.vs-code-prettier-eslint
windsurf --install-extension sdras.night-owl
windsurf --install-extension segerdekort.angular-cli
windsurf --install-extension shardulm94.trailing-spaces
windsurf --install-extension shd101wyy.markdown-preview-enhanced
windsurf --install-extension simontest.simontest
windsurf --install-extension sonarsource.sonarlint-vscode
windsurf --install-extension steoates.autoimport
windsurf --install-extension stringham.move-ts
windsurf --install-extension stuart.unique-window-colors
windsurf --install-extension tomoki1207.pdf
windsurf --install-extension usernamehw.errorlens
windsurf --install-extension visualstudioexptteam.intellicode-api-usage-examples
windsurf --install-extension vscode-icons-team.vscode-icons
windsurf --install-extension waderyan.gitblame
windsurf --install-extension wayou.vscode-todo-highlight
windsurf --install-extension whizkydee.material-palenight-theme
windsurf --install-extension wix.vscode-import-cost
windsurf --install-extension xabikos.javascriptsnippets
windsurf --install-extension yoavbls.pretty-ts-errors
windsurf --install-extension yzhang.markdown-all-in-one
windsurf --install-extension zhuangtongfa.material-theme
windsurf --install-extension zignd.html-css-class-completion
