#!/usr/bin/env bash
set -euo pipefail

echo "Linking dotfiles"
pwd

cd env/dotfiles || exit 1
for i in *; do
    if [ -d "$i" ]; then
        echo "Stowing $i"
        rm -fr "$HOME"/.config/$i
stow --restow --target=$HOME $i
    fi
done

cd ../.. || exit 1

echo "Stowing dotfiles"

rm -rf "$HOME"/personal/nvim
git clone https://github.com/javiersanzgarcia/LazyVIM.git "$HOME"/personal/nvim

cp -r "$HOME"/personal/nvim "$HOME"/.config
chmod -R 777 "$HOME"/.config/nvim
rm -rf "$HOME"/personal
