#!/usr/bin/env bash

echo "Linking dotfiles"
pwd

cd env/dotfiles || exit 1
stow atuin
cd ../.. || exit 1

echo "Stowing dotfiles"

if [ ! -d "$HOME"/personal/nvim ]; then
  rm -rf "$HOME"/personal/nvim
  git clone https://github.com/javiersanzgarcia/LazyVim.git "$HOME"/personal/nvim
fi

rm -rf "$HOME"/.config/nvim
cp -r "$HOME"/personal/nvim "$HOME"/.config
chmod -R 777 "$HOME"/.config/nvim
rm -rf "$HOME"/personal

source ~/.zshrc
