#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Ubuntu"
sudo apt -y install zsh fonts-powerline

hash -r
chsh -s "$(which zsh)"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

ln -nf "$script_dir/env/.oh-my-zsh" ~/
ln -nf "$script_dir/env/clean.sh" ~/
ln -nf "$script_dir/env/keyboard_permissions.sh" ~/
ln -nf "$script_dir/env/mount.sh" ~/
ln -nf "$script_dir/env/.zshrc" ~/
ln -nf "$script_dir/env/.p10k.zsh" ~/

git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

source ~/.zshrc
echo "source ~/.zshrc"
